import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { mapPermissionMode } from './claude';
import { readSessionSummary } from './jsonl';

// -- Fixture helpers (same minimal records as jsonl.spec.ts) --

function userRecord(overrides: Record<string, unknown> = {}): string {
	return JSON.stringify({
		type: 'user',
		uuid: 'u1',
		parentUuid: null,
		timestamp: '2026-01-01T00:00:00.000Z',
		sessionId: 'sess-1',
		slug: null,
		cwd: 'C:\\project',
		gitBranch: 'main',
		isSidechain: false,
		message: { role: 'user', content: 'hello' },
		...overrides
	});
}

function assistantRecord(overrides: Record<string, unknown> = {}): string {
	return JSON.stringify({
		type: 'assistant',
		uuid: 'a1',
		parentUuid: 'u1',
		timestamp: '2026-01-01T00:00:01.000Z',
		isSidechain: false,
		message: {
			role: 'assistant',
			model: 'claude-opus-4-6',
			content: [{ type: 'text', text: 'hi there' }],
			stop_reason: 'end_turn'
		},
		...overrides
	});
}

function fileHistorySnapshot(): string {
	return JSON.stringify({
		type: 'file-history-snapshot',
		messageId: 'fhs-1',
		snapshot: {},
		isSnapshotUpdate: false
	});
}

// -- Test setup --

let tempDir: string;

beforeEach(() => {
	tempDir = join(tmpdir(), `claude-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
	mkdirSync(tempDir, { recursive: true });
});

afterEach(() => {
	rmSync(tempDir, { recursive: true, force: true });
});

function writeFixture(name: string, lines: string[]): string {
	const filePath = join(tempDir, name);
	writeFileSync(filePath, lines.join('\n') + '\n');
	return filePath;
}

// -- Tests --

describe('mapPermissionMode', () => {
	it('maps "default" to "standard"', () => {
		expect(mapPermissionMode('default')).toBe('standard');
	});

	it('maps "acceptEdits" to "standard"', () => {
		expect(mapPermissionMode('acceptEdits')).toBe('standard');
	});

	it('maps "plan" to "plan"', () => {
		expect(mapPermissionMode('plan')).toBe('plan');
	});

	it('maps "bypassPermissions" to "yolo"', () => {
		expect(mapPermissionMode('bypassPermissions')).toBe('yolo');
	});

	it('maps null to null', () => {
		expect(mapPermissionMode(null)).toBeNull();
	});

	it('maps unknown values to null', () => {
		expect(mapPermissionMode('something-new')).toBeNull();
	});
});

describe('session content detection', () => {
	it('meta-only session is detected as having no content', async () => {
		// Reproduces: session c415e145 which only has /clear commands
		// and shows a blank detail page
		const filePath = writeFixture('meta-only.jsonl', [
			fileHistorySnapshot(),
			userRecord({
				message: {
					role: 'user',
					content:
						'<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>'
				}
			}),
			userRecord({
				message: {
					role: 'user',
					content: '<command-name>/clear</command-name>\n<command-message>clear</command-message>'
				}
			}),
			userRecord({
				message: {
					role: 'user',
					content: '<local-command-stdout></local-command-stdout>'
				}
			}),
			fileHistorySnapshot()
		]);

		const summary = await readSessionSummary(filePath);
		expect(summary.hasContent).toBe(false);
	});

	it('session with real conversation is detected as having content', async () => {
		const filePath = writeFixture('real.jsonl', [
			userRecord({ message: { role: 'user', content: 'fix the login bug' } }),
			assistantRecord()
		]);

		const summary = await readSessionSummary(filePath);
		expect(summary.hasContent).toBe(true);
	});

	it('session with only file-history-snapshot records has no content', async () => {
		const filePath = writeFixture('snapshots-only.jsonl', [
			fileHistorySnapshot(),
			fileHistorySnapshot()
		]);

		const summary = await readSessionSummary(filePath);
		expect(summary.hasContent).toBe(false);
	});
});
